version: '3'

services:
  service-discovery:
    image: ptb-gp-ss2019.archi-lab.io/service-discovery
    ports:
      - "8761:8761"
    restart: always
    networks:
      - ptb

networks:
  ptb:
    external: true
