version: "3.6"

services:

  service-discovery:
    image: docker.nexus.archi-lab.io/archilab/prox-service-discovery
    restart: always
    networks:
      - prox

networks:
  prox:
    external: true
