version: "3.6"

services:

  service-discovery:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    image: docker.nexus.archi-lab.io/archilab/${IMAGE}:${TAG}
    networks:
      - prox

networks:
  prox:
    external: true
